config/routes.rb
Rails.application.routes.draw do
  resources :seens, only: [:create, :index]
  resources :announcements
  devise_for :accounts
  get '/about', to: 'home#about'
  root to: "home#index"
end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :announcements, dependent: :destroy
  has_many :seens, dependent: :destroy

end

app/models/announcement.rb
class Announcement < ApplicationRecord
    validates :account, presence: true
    validates :content, presence: true, length: { maximum: 140 }
    validates :date, presence: true

    has_many :seens, dependent: :destroy
    belongs_to :account

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/seen.rb
class Seen < ApplicationRecord
  validates :account, uniqueness: { scope: :announcement }

  belongs_to :account
  belongs_to :announcement
end

app/controllers/announcements_controller.rb
class AnnouncementsController < ApplicationController
  before_action :authenticate_account!, :set_announcement, only: %i[ show edit update destroy ]

  # GET /announcements or /announcements.json
  def index
    @announcements = current_account.announcements
  end

  # GET /announcements/1 or /announcements/1.json
  def show
  end

  # GET /announcements/new
  def new
    @announcement = Announcement.new
  end

  # GET /announcements/1/edit
  def edit
  end

  # POST /announcements or /announcements.json
  def create
    @announcement = Announcement.new(announcement_params)

    respond_to do |format|
      if @announcement.save
        format.html { redirect_to announcement_url(@announcement), notice: "Announcement was successfully created." }
        format.json { render :show, status: :created, location: @announcement }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /announcements/1 or /announcements/1.json
  def update
    respond_to do |format|
      if @announcement.update(announcement_params)
        format.html { redirect_to announcement_url(@announcement), notice: "Announcement was successfully updated." }
        format.json { render :show, status: :ok, location: @announcement }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @announcement.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /announcements/1 or /announcements/1.json
  def destroy
    @announcement.destroy

    respond_to do |format|
      format.html { redirect_to announcements_url, notice: "Announcement was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_announcement
      @announcement = Announcement.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def announcement_params
      params.require(:announcement).permit(:content, :date, :account, :account_id)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?

    protected
  
    def configure_permitted_parameters
      attributes = [:first_name, :last_name]
      devise_parameter_sanitizer.permit(:sign_up, keys: attributes)
      devise_parameter_sanitizer.permit(:account_update, keys: attributes)
    end

    def after_sign_in_path_for(resource)
        return root_path
    end
    
    def after_sign_out_path_for(resource)
        return root_path
    end


end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    ad_ids = []
    if account_signed_in?
      tags = current_account.seens
      tags.each do |single|
        ad_ids.append(single.announcement.id)
      end
    end
    if ad_ids.count > 0
      @anuncios = Announcement.where.not('id IN (?)', ad_ids).order(created_at: :desc)
    else
      @anuncios = Announcement.order(created_at: :desc)
    end
  end

  def about
  end
end

app/controllers/seens_controller.rb
class SeensController < ApplicationController
    def create
      Seen.create(announcement: announcement, account: current_account)
      redirect_to root_path
    end

    def index
      @announcements = Announcement.joins(:seens).where({ seens: {account_id: current_account}})
    end

    private

    def announcement
      Announcement.find(params[:announcement_id])
    end
  end

app/helpers/announcements_helper.rb
module AnnouncementsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/announcements/_form.html.erb
<% if account_signed_in? %>
  <%= form_with(model: announcement) do |form| %>
  <% if announcement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(announcement.errors.count, "error") %> prohibited this announcement from being saved:</h2>

      <ul>
        <% announcement.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="field">
    <%= form.label :date, 'Expiration date' %>
    <%= form.datetime_field :date, as: :date_time_picker %>
  </div>

  <div class="field">
    <%= form.hidden_field :account_id, value: current_account.id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>
<%else %>
  <p>Please Sign Up or Sign In to view the content.</p>

  <h2><%= link_to "Sign up", new_account_registration_path%>

<% end %>

app/views/announcements/edit.html.erb
<h1>Editing Announcement</h1>

<%= render 'form', announcement: @announcement %>

<%= link_to 'Show', @announcement %> |
<%= link_to 'Back', announcements_path %>

app/views/announcements/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Announcements</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Content</th>
      <th>Date</th>
      <th>Account</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @announcements.each do |announcement| %>
      <tr>
        <td><%= announcement.id %></td>
        <td><%= announcement.content %></td>
        <td><%= announcement.date %></td>
        <td><%= announcement.account.email %></td>
        <td><%= link_to 'Show', announcement %></td>
        <td><%= link_to 'Edit', edit_announcement_path(announcement) %></td>
        <td><%= link_to 'Destroy', announcement, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Announcement', new_announcement_path %>

app/views/announcements/new.html.erb
<h1>New Announcement</h1>

<%= render 'form', announcement: @announcement %>

<%= link_to 'Back', announcements_path %>

app/views/announcements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Content:</strong>
  <%= @announcement.content %>
</p>

<p>
  <strong>Date:</strong>
  <%= @announcement.date %>
</p>

<p>
  <strong>Account:</strong>
  <%= @announcement.account.email %>
</p>

<%= link_to 'Edit', edit_announcement_path(@announcement) %> |
<%= link_to 'Back', announcements_path %>

app/views/home/about.html.erb
<h2 class="text-center">Diagrama ER Database</h2>


<p class="text-center">Este es el diagrama de entidad relacion para el ejemplo 2 sobre  la
app de anuncios</p>

<%= link_to image_tag("example_2_hogaru.png", alt: "ER-Diagram", class: "thumbnail"), "/about" %>

app/views/home/index.html.erb
<h1 class="text-center">Todos los anuncios</h1>
<% if account_signed_in? %>
  <% if !current_account.first_name? %>
    <p class="alert-box callout info">Edita tu perfil para que aparezca tu
    nombre no tu correo, en los anuncios <%= link_to 'Edit profile', edit_account_registration_path, :class => 'navbar-link' %> </p>
  <% end %>
<% end %>

<% @anuncios.each do |single| %>
<% if single.date.to_date >= Time.now.to_date %>
  <div class="callout secondary">
    <p> <%= single.content %> </p>
    <p> <%= distance_of_time_in_words(single.created_at, Time.now)%> By: <% if single.account.first_name? %>
      <%= single.account.first_name %> <%= single.account.last_name %>
      <% else %>
      <%= single.account.email %>
      <%end%>
    </p>
    <% if account_signed_in? %>
      <% if current_account.id != single.account.id %>
        <p class="text-right">
          <%= link_to 'Marcar como visto!', seens_path(announcement_id: single.id), method: :post %>
        </p>
      <% end %>
    <% end %>
  </div>
<% end %>
<% end %>

app/views/layouts/_footer.html.erb
<div id="footer">
    Carlos Rocha 2022
</div>

app/views/layouts/_navbar.html.erb
<div class="title-bar" data-responsive-toggle="responsive-menu" data-hide-for="medium">
  <button class="menu-icon" type="button" data-toggle="responsive-menu"></button>
  <div class="title-bar-title">Menu</div>
</div>

<div class="top-bar" id="responsive-menu">
  <div class="top-bar-left">
    <ul class="menu">
      <li class="menu-text">Anuncios</li>
      <li><a href="/">Home</a></li>
      <% if account_signed_in? %>
        <li> <%= link_to 'Create Announcement', new_announcement_path %></li>
        <li> <%= link_to 'My announcements',  announcements_path, :class => 'navbar-link' %></li>
      <% end %>
      <li> <%= link_to 'About', about_path %> </li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="dropdown menu" data-dropdown-menu>
    <% if account_signed_in? %>
    <li>
        <a href="#"><% if current_account.first_name? %>
        <%= current_account.first_name %> <%= current_account.last_name %></a>
        <% else %>
          <%= current_account.email %></a>
          <% end %>
        <ul class="menu vertical">
          <li><%= link_to 'Edit profile', edit_account_registration_path, :class => 'navbar-link' %></li>
          <li> <%= link_to 'Seen announcements ', seens_path, :class => 'navbar-link' %> </li>
          <li><%= link_to "Logout", destroy_account_session_path, method: :delete, :class => 'navbar-link' %></li>
        </ul>
    </li>
    <% else %>
        <li><%= link_to 'Sign Up', new_account_registration_path, :class => 'navbar-link' %></li>
        <li><%= link_to 'Log In', account_session_path, :class => 'navbar-link' %></li>
    <% end %>
    </ul>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Anuncios-examen" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <div class="grid-container">
        <%= render 'layouts/navbar' %>
        <% if notice %>
          <p class="alert-box callout success"><%= notice %></p>
        <% end %>
        <% if alert %>
          <p class="alert-box callout alert"><%= alert %></p>
        <% end %>
        <%= yield %>
        <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/seens/index.html.erb
<h1 class='text-center'>Seen Announcements</h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>Content</th>
      <th>Date Expiration</th>
      <th>Account</th>
    </tr>
  </thead>

  <tbody>
    <% @announcements.each do |announcement| %>
      <tr>
        <td><%= announcement.id %></td>
        <td><%= announcement.content %></td>
        <td><%= announcement.date %></td>
        <td><%= announcement.account.email %></td>
      </tr>
    <% end %>
  </tbody>
</table>